# Generated by Django 4.0.5 on 2022-07-02 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0017_remove_order_cliente_remove_orderitem_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Orden',
                'db_table': 'Orden',
                'ordering': ['Total'],
            },
        ),
        migrations.CreateModel(
            name='OrdenDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idOrden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.orden')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.productos')),
            ],
            options={
                'verbose_name': 'OrdenDetalle',
                'verbose_name_plural': 'OrdenDetalle',
                'db_table': 'OrdenDetalle',
                'ordering': ['idOrden'],
            },
        ),
        migrations.CreateModel(
            name='ComparacionPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precioAntiguo', models.IntegerField()),
                ('precioNuevo', models.IntegerField()),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.productos')),
            ],
            options={
                'verbose_name': 'ComparacionPrecios',
                'verbose_name_plural': 'ComparacionPrecios',
                'db_table': 'ComparacionPrecios',
                'ordering': ['fecha'],
            },
        ),
    ]
